# Julia Basics


### What is Julia

- developped at MIT on top of opensource technologies:
    - linux / git
- syntax inspired by Matlab but:
    - more consistent
    - lots of features from high level languages
- opensource and free


Some useful links from QuantEcon:

* [Julia cheatsheet](https://cheatsheets.quantecon.org/julia-cheatsheet.html)
* [Julia-Matlab comparison](https://cheatsheets.quantecon.org/index.html)
* [Julia essentials](https://julia.quantecon.org/getting_started_julia/julia_essentials.html)
* [Vectors, arrays and matrices](https://julia.quantecon.org/getting_started_julia/fundamental_types.html)

Excellent resources at: [julialang](https://julialang.org/learning/)
- checkout JuliaAcademy, it's free
- ongoing [MOOC](https://computationalthinking.mit.edu/Spring21/) at MIT

### Syntax Review

#### Variable assignment

Assignement operator is = (equality is ==, identity is ===)

In [1]:
# Assign the value 10 to the variable x
x = 10

10

In [2]:
2 == 3

false

In [5]:
# Variable names can have Unicode characters
# To get ϵ in the REPL, type \epsilon<TAB>
ϵ = 1e-4
β = 0.9

0.9

Default semantic is pass-by-reference:

In [6]:
a = [1,2,3,4]
b = a
a[1] = 10
b

4-element Vector{Int64}:
 10
  2
  3
  4

To work on a copy: `copy` or `deepcopy`

In [17]:
a = [1,2,3,4]
b = copy(a)
a[1]=10
b

4-element Vector{Int64}:
 1
 2
 3
 4

In [7]:
a .== b

4-element BitVector:
 1
 1
 1
 1

In [8]:
a === b

true

#### Basic types

In [9]:
# for any object `typeof` returns the type
typeof

typeof (built-in function)

In [10]:
typeof(a)

Vector{Int64} (alias for Array{Int64, 1})

#### Numbers

In [21]:
y = 2 + 2

4

In [12]:
a_i = 1000
a_f = 1000.0

1000.0

In [13]:
bitstring(a_f)

"0100000010001111010000000000000000000000000000000000000000000000"

In [16]:
-a_i

-1000

In [17]:
0.34*23

7.82

In [18]:
3/4

0.75

In [19]:
# Scalar multiplication doesn't require *
3(4 - 2)

6

In [20]:
x = 4
2x

8

In [21]:
typeof(x)

Int64

In [22]:
sizeof(a)

32

#### Booleans

In [23]:
false

false

Equality

In [24]:
0 == 1

false

In [25]:
2 != 3

true

In [26]:
3 <= 4

true

Identity

In [27]:
a = [34, 35]
b = [34, 35]
c = a

2-element Vector{Int64}:
 34
 35

In [28]:
c === a

true

In [29]:
b === a

false

Boolean operator

In [30]:
true && false

false

In [31]:
true || false

true

In [32]:
!true

false

#### Strings

In [33]:
# Strings are written using double quotes
str = "This is a string 🦈"

"This is a string 🦈"

In [34]:
ch = 'k' # this is a character

'k': ASCII/Unicode U+006B (category Ll: Letter, lowercase)

In [35]:
# Strings can also contain Unicode characters
fancy_str = "α is a string"

"α is a string"

In [36]:
# String interpolation using $
# The expression in parentheses is evaluated and the result is 
# inserted into the string
a = 2+2
"2 + 2 = $(a)"

"2 + 2 = 4"

In [37]:
println("It took me $(a) iterations")

It took me 4 iterations


In [38]:
# String concatenation using *
"hello" * "world"

"helloworld"

In [39]:
println("hello ", "world")

hello world


#### Arrays

Julia has one-dimensional arrays. They are also called Vector.

In [40]:
A = Float64[1, 4]

2-element Vector{Float64}:
 1.0
 4.0

All elements have the same type:

In [41]:
A = [1, 1.4]

2-element Vector{Float64}:
 1.0
 1.4

In [42]:
eltype(A)

Float64

In [43]:
typeof(A) 

Vector{Float64} (alias for Array{Float64, 1})

In [46]:
A''

2-element Vector{Float64}:
 1.0
 1.4

To get the size of an array:

In [47]:
size(A)

(2,)

Arrays are *mutable*

In [48]:
A[1] = 10

10

In [49]:
A

2-element Vector{Float64}:
 10.0
  1.4

Julia has one-based indexing: you refer to the first element as 1 ($\neq$ zero-based indexing in C or Python)

In [50]:
A[2]

1.4

Arrays are mutable and their size can be changed too:

In [51]:
push!(A, 29)

3-element Vector{Float64}:
 10.0
  1.4
 29.0

In [52]:
A

3-element Vector{Float64}:
 10.0
  1.4
 29.0

Two comments:
- the `push!` operation is *fast*
- `!` is a julia convention to express the fact that `push!` mutates its first argument

#### tuples

In [53]:
size(A)  # is a tupled

(3,)

In [54]:
# you can create tuples with (,,,)
t = (1,2,3,4)


(1, 2, 3, 4)

In [55]:
t

(1, 2, 3, 4)

tuples differ from arrays in two ways:
- they are immutable
- they can contain non-homogenous objects

In [56]:
t[1]

1

In [217]:
t[1] = 2

LoadError: MethodError: no method matching setindex!(::NamedTuple{(:a, :b, :c), Tuple{Int64, Int64, Int64}}, ::Int64, ::Int64)

In [58]:
tt = (1, "1", [1])

(1, "1", [1])

In [59]:
typeof(tt)

Tuple{Int64, String, Vector{Int64}}

#### Named tuples

Named tuples are tuple with field names. Note that the semi-colon separates positional arguments from keyword arguments.

In [60]:
"jlij"

"jlij"

#### Array operations

##### Other ways to construct arrays:

In [64]:
# zero array
t = zeros(2,3)
t[1,2] = 23.2
t

2×3 Matrix{Float64}:
 0.0  23.2  0.0
 0.0   0.0  0.0

In [65]:
# random array (uniform distribution)
t= rand(3,3)
t

3×3 Matrix{Float64}:
 0.743555   0.671428  0.00145982
 0.0194631  0.250996  0.435498
 0.954361   0.251996  0.301447

In [66]:
# random array (normal distribution)
t= randn(3,3)
t

3×3 Matrix{Float64}:
  0.839846   1.02046    0.478943
 -1.33357   -0.654968  -0.38329
  0.738567   0.78214    0.196234

Vectorized operations take a ., even comparisons (pointwise operations)

In [67]:
B = [1 2 ; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [68]:
B .* B

2×2 Matrix{Int64}:
 1   4
 9  16

In [69]:
f(x) = x^2+1

f (generic function with 1 method)

In [70]:
f(43.0)

1850.0

In [71]:
f.(B)

2×2 Matrix{Int64}:
  2   5
 10  17

Elements are always accessed with square brackets:

In [72]:
B = [1 2 3; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [ ]:
You get element $B_{ij}$ with `B[i,j]`

In [73]:
B[4]

5

You select a whole row/column with `:`

In [74]:
B

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [75]:
B[:,1]

2-element Vector{Int64}:
 1
 4

In [76]:
B[1,:]

3-element Vector{Int64}:
 1
 2
 3

In [77]:
B[:,1:2]

2×2 Matrix{Int64}:
 1  2
 4  5

In [78]:
B[:,1:end-1]

2×2 Matrix{Int64}:
 1  2
 4  5

#### Control flow

Conditions

In [79]:
x = 0
if x<0
    # block
    println("x is negative")
elseif (x > 0) # optional and unlimited
    println("x is positive")
else         # optional
    println("x is zero")
end

x is zero


While

In [80]:
i = 3
while i > 0
    println(i)
    i -= 1 # decrement
end

3
2
1


In [81]:
# Iterate through ranges of numbers
for i ∈ (1:3)
    println(i)
end

1
2
3


In [82]:
# Iterate through arrays
cities = ["Boston", "New York", "Philadelphia"]
for city in cities
    println(city)
end

Boston
New York
Philadelphia


In [83]:
cities

3-element Vector{String}:
 "Boston"
 "New York"
 "Philadelphia"

In [84]:
states = ["Massachussets", "New York", "Pennsylvania"]

3-element Vector{String}:
 "Massachussets"
 "New York"
 "Pennsylvania"

In [86]:
two_by_two_iterable = zip(cities, states)

zip(["Boston", "New York", "Philadelphia"], ["Massachussets", "New York", "Pennsylvania"])

In [87]:
collect(two_by_two_iterable)

3-element Vector{Tuple{String, String}}:
 ("Boston", "Massachussets")
 ("New York", "New York")
 ("Philadelphia", "Pennsylvania")

In [98]:
# Iterate through arrays of tuples using zip
for kw in zip(cities, states)
    println(kw)
end

("Boston", "Massachussets")
("New York", "New York")
("Philadelphia", "Pennsylvania")


In [79]:
# Iterate through arrays of tuples using zip
for (city, state) in zip(cities, states)
    println("$city, $state")
end

Boston, Massachussets
New York, New York
Philadelphia, Pennsylvania


In [88]:
# Iterate through arrays and their indices using enumerate
for (i, city) in enumerate(cities)
    println("City $i is $city")
end

City 1 is Boston
City 2 is New York
City 3 is Philadelphia


#### List comprehensions

In [99]:
[i^2 for i  ∈ 1:10] # collect with comprehension syntax

10-element Vector{Int64}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [89]:
[1:10 ...]  # unpack operator

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [93]:
[i^2 for i=1:10 if mod(i,2)==0]

5-element Vector{Int64}:
   4
  16
  36
  64
 100

#### Iterators

Like pyton, an "iterator" can be created with round brackets and can be composed together.

In [94]:
iterator = ( i^2 for i=1:10 if mod(i,2)==0 )

Base.Generator{Base.Iterators.Filter{var"#18#20", UnitRange{Int64}}, var"#17#19"}(var"#17#19"(), Base.Iterators.Filter{var"#18#20", UnitRange{Int64}}(var"#18#20"(), 1:10))

### Data Types and multiple dispatch

#### Composite types

A **composite type** is a collection of named fields that can be treated as a single value. They bear a passing resemblance to MATLAB structs.

All fields must be declared ahead of time. The double colon, `::`, constrains a field to contain values of a certain type. This is optional for any field.

In [96]:
# Type definition with 4 fields
struct ParameterFree
    value  
    transformation  
    tex_label
    description 
end

In [97]:
pf = ParameterFree("1", x->x^2, "\\sqrt{1+x^2}", ("a",1))

ParameterFree("1", var"#23#24"(), "\\sqrt{1+x^2}", ("a", 1))

In [102]:
pf.value

"1"

Two reasons to create structures:
- syntactic shortcut (you access the fields with .)
- specify the types of the fields

In [120]:
# Type definition
struct Parameter
    value ::Float64
    transformation ::Function # Function is a type!
    tex_label::String
    description::String
    stddev::Float64
end

In [121]:
p = Parameter("1", x->x^2, "\\sqrt{1+x^2}", "Crucial Parameter", 5)

LoadError: MethodError: Cannot `convert` an object of type String to an object of type Float64
Closest candidates are:
  convert(::Type{T}, ::T) where T<:Number at number.jl:6
  convert(::Type{T}, ::Number) where T<:Number at number.jl:7
  convert(::Type{T}, ::Base.TwicePrecision) where T<:Number at twiceprecision.jl:250
  ...

In [122]:
p = Parameter(0.43, x->x^2, "\\sqrt{1+x^2}", "This is a description", 5)

Parameter(0.43, var"#45#46"(), "\\sqrt{1+x^2}", "This is a description", 5.0)

In [123]:
p.value

0.43

When a type with $n$ fields is defined, a constructor (function that creates an instance of that type) that takes $n$ ordered arguments is automatically created. Additional constructors can be defined for convenience.

In [125]:
# Creating an instance of the Parameter type using the default
# constructor
β = Parameter(0.9, identity, "\\beta", "Discount rate", 1)

Parameter(0.9, identity, "\\beta", "Discount rate", 1.0)

In [139]:
function Parameter(value)
    return Parameter(value, x->x^2, "x", "Anonymous",1)
end

Parameter

In [140]:
Parameter(0.4)

Parameter(0.4, var"#53#54"(), "x", "Anonymous", 1.0)

In [219]:
# Alternative constructors end with an appeal to the default
# constructor
function Parameter(value::Float64, tex_label::String)
    transformation = identity
    description = "No description available"
    return Parameter(value, transformation, tex_label, description,1)
end

α = Parameter(0.5, "\alpha")

Parameter(0.5, identity, "\alpha", "No description available", 1.0)

Now the function `Parameter` has two different `methods` with different signatures:

In [220]:
methods(Parameter)

# 5 methods for type constructor:
[1] Parameter(value::Float64, transformation::Function, tex_label::String, description::String, stddev::Float64) in Main at In[120]:3
[2] Parameter(value::Float64, tex_label::String) in Main at In[219]:3
[3] Parameter(value) in Main at In[139]:1
[4] Parameter(value, transformation, tex) in Main at In[130]:1
[5] Parameter(value, transformation, tex_label, description, stddev) in Main at In[120]:3

We have seen that a function can have several implementations, called methods, for different number of arguments, 
or for different types of arguments.

In [145]:
fun(x::Int64, y::Int64) = x^3 + y

fun (generic function with 1 method)

In [146]:
fun(x::Float64, y::Int64) = x/2 + y

fun (generic function with 2 methods)

In [147]:
fun(2, 2)

10

In [148]:
fun(2.0, 2)

3.0

In [221]:
α.tex_label

"\alpha"

In [222]:
# Access a particular field using .
α.value

0.5

### Mutable vs non mutable types


by default structures in Julia are non-mutable

In [153]:
p.value = 3.0

LoadError: setfield! immutable struct of type Parameter cannot be changed

In [154]:
mutable struct Params
    x:: Float64
    y:: Float64
end

In [155]:
pos = Params(0.4, 0.2)

Params(0.4, 0.2)

In [223]:
pos.x = 0.5

0.5

### Parameterized Types

**Parameterized types** are data types that are defined to handle values identically regardless of the type of those values.

Arrays are a familiar example. An `Array{T,1}` is a one-dimensional array filled with objects of any type `T` (e.g. `Float64`, `String`).

In [157]:
[45,76]

2-element Vector{Int64}:
 45
 76

In [158]:
[45,76.0]

2-element Vector{Float64}:
 45.0
 76.0

In [159]:
# Defining a parametric point
struct Duple{T} # T is a parameter to the type Duple
    x::T
    y::T
end

In [136]:
Duple(3, 3)

Duple{Int64}(3, 3)

In [160]:
Duple(3.0, -1.0)

Duple{Float64}(3.0, -1.0)

In [161]:
Duple(3.0, -1)

LoadError: MethodError: no method matching Duple(::Float64, ::Int64)
Closest candidates are:
  Duple(::T, ::T) where T at In[159]:3

This single declaration defines an unlimited number of new types: `Duple{String}`, `Duple{Float64}`, etc. are all immediately usable.

We can also restrict the type parameter `T`:

In [165]:
typeof("S") <: Number

false

In [166]:
typeof(4) <: Number

true

In [169]:
# T can be any subtype of Number, but nothing else
struct PlanarCoordinate{T<:Number}
    x::T
    y::T
end

In [170]:
PlanarCoordinate("4th Ave", "14th St")

LoadError: MethodError: no method matching PlanarCoordinate(::String, ::String)

In [171]:
PlanarCoordinate(2//3, 8//9)

PlanarCoordinate{Rational{Int64}}(2//3, 8//9)

Arrays are an exemple of mutable, parameterized types

### Why Use Types?

You can write all your code without thinking about types at all. If you do this, however, you’ll be missing out on some of the biggest benefits of using Julia.

If you understand types, you can:

- Write faster code
- Write expressive, clear, and well-structured programs (keep this in mind when we talk about functions)
- Reason more clearly about how your code works

Even if you only use built-in functions and types, your code still takes advantage of Julia’s type system. That’s why it’s important to understand what types are and how to use them.

In [172]:
# Example: writing type-stable functions
function sumofsins_unstable(n::Integer)  
    sum = 0:: Integer
    for i in 1:n  
        sum += sin(3.4)  
    end  
    return sum 
end  

function sumofsins_stable(n::Integer)  
    sum = 0.0 :: Float64
    for i in 1:n  
        sum += sin(3.4)  
    end  
    return sum 
end

# Compile and run
sumofsins_unstable(Int(1e5))
sumofsins_stable(Int(1e5))

-25554.110202663698

In [173]:
@time sumofsins_unstable(Int(1e5))

  0.000224 seconds


-25554.110202663698

In [174]:
@time sumofsins_stable(Int(1e5))

  0.000112 seconds


-25554.110202663698

In `sumofsins_stable`, the compiler is guaranteed that `sum` is of type `Float64` throughout; therefore, it saves time and memory. On the other hand, in `sumofsins_unstable`, the compiler must check the type of `sum` at each iteration of the loop. 

### Multiple Dispatch

So far we have defined functions over argument lists of any type. Methods allow us to define functions “piecewise”. For any set of input arguments, we can define a **method**, a definition of one possible behavior for a function.

In [175]:
# Define one method of the function print_type
function print_type(x::Number)
    println("$x is a number")
end

print_type (generic function with 1 method)

In [176]:
# Define another method
function print_type(x::String)
    println("$x is a string")
end

print_type (generic function with 2 methods)

In [177]:
# Define yet another method
function print_type(x::Number, y::Number)
    println("$x and $y are both numbers")
end

print_type (generic function with 3 methods)

In [224]:
# See all methods for a given function
methods(print_type)

# 3 methods for generic function "print_type":
[1] print_type(x::Number) in Main at In[175]:2
[2] print_type(x::String) in Main at In[176]:2
[3] print_type(x::Number, y::Number) in Main at In[177]:2

Julia uses **multiple dispatch** to decide which **method** of a **function** to execute when a function is applied. In particular, Julia compares the types of _all_ arguments to the signatures of the function’s methods in order to choose the applicable one, not just the first (hence "multiple").

In [179]:
print_type(5)

5 is a number


In [180]:
print_type("foo")

foo is a string


In [181]:
print_type([1, 2, 3])

LoadError: MethodError: no method matching print_type(::Vector{Int64})
Closest candidates are:
  print_type(::Number) at In[175]:2
  print_type(::String) at In[176]:2
  print_type(::Number, ::Number) at In[177]:2

#### Other types of functions

Julia supports a short function definition for one-liners

In [182]:
f(x) = x^3

f (generic function with 1 method)

In [183]:
f(3.0)

27.0

In [184]:
f(x::Float64) = x^2.0
f(x::Int64) = x^3

f (generic function with 3 methods)

In [185]:
methods(f)

# 3 methods for generic function "f":
[1] f(x::Float64) in Main at In[184]:1
[2] f(x::Int64) in Main at In[184]:2
[3] f(x) in Main at In[182]:1

As well as a special syntax for anonymous functions

In [186]:
u -> u^2

#55 (generic function with 1 method)

In [187]:
((u,v) -> (u+v)^2)( 4.4, 4)

70.56

In [188]:
map(u->u^2, [1,2,3,4])

4-element Vector{Int64}:
  1
  4
  9
 16

In [190]:
maximum(u^2 for u ∈ A)

841.0

### Keyword arguments and optional arguments

In [191]:
g(a,b,c=true; algo="newton") = c ? a + b : a-b

g (generic function with 2 methods)

In [192]:
g(2,3)

5

In [193]:
g(2,3, true; algo = :JI)

5

### Packing/unpacking


In [194]:
t = (1,2,4)

(1, 2, 4)

In [195]:
a,b,c = t

(1, 2, 4)

In [196]:
[(1:10)...]

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [197]:
cat([4,3], [0,1]; dims=1)

4-element Vector{Int64}:
 4
 3
 0
 1

In [198]:
l = [[4,3], [0,1], [0, 0], [1, 1]]
# how do I concatenate it ?

cat(l...; dims=1) ### see python's f(*s)

8-element Vector{Int64}:
 4
 3
 0
 1
 0
 0
 1
 1

Since 1.8, there is a special syntax to create named tuple, and unpack objects.

In [199]:
a = 1
b = 2
c = 3
t = (;a, b, c) # equivalent to (;a=1,b=2,c=3)

(a = 1, b = 2, c = 3)

In [200]:
a = b = c = 0

0

### Writing Julian Code

As we've seen, you can use Julia just like you use MATLAB and get faster code. However, to write faster and _better_ code, attempt to write in a “Julian” manner:

- Define composite types as logically needed
- Write type-stable functions for best performance
- Take advantage of multiple dispatch to write code that looks like math
- Add methods to existing functions

## Exercise:

Define 3x3 matrix `M` with biggest eigenvalue smaller than 1. 
Consider Ar1 process $X_t = M X_{t-1} + E_t$ where E_t follows a standard normal distribution.
Simulate for T=1000 periods starting with $X_0=[0,0,0]$. Compute 1000 draws to approximate the standard deviation of the ergodic distribution.




In [204]:
M = [ 0.9 0.05 0.05 ; 0.05 0.8 0.05 ; 0.05 0.9 0.05]

3×3 Matrix{Float64}:
 0.9   0.05  0.05
 0.05  0.8   0.05
 0.05  0.9   0.05

In [205]:
function simulate(M, x0=rand(size(M,1)); T=100000)
    p,q = size(M)
    for t =1:T
        x0 = M*x0 + randn(p)
    end
    x0
end

simulate (generic function with 2 methods)

In [206]:
@time simulate(M)

  0.250946 seconds (856.28 k allocations: 64.524 MiB, 5.76% gc time, 82.60% compilation time)


3-element Vector{Float64}:
 2.4523142328654015
 3.653235560782421
 3.8133153297086095

In [211]:
function simulate_inplace(M, x0=rand(size(M,1)); T=100000)
    p,q = size(M)
    x1 = copy(x0)
    for t =1:T
        x1[:] .= M*x0 + randn(p)
        x0,x1 = x1,x0
    end
    x0
end

simulate_inplace (generic function with 2 methods)

In [50]:
@time simulate_inplace(M)

  0.050308 seconds (300.00 k allocations: 22.888 MiB, 36.60% gc time)


3-element Vector{Float64}:
 -5.441608579429695
 -2.9048356249869536
 -2.7298959624035994

In [213]:
function simulate_byhand(M, x0=rand(size(M,1)); T=100000)
    p,q = size(M)
    x1 = copy(x0)
    m11, m12, m13 = M[1,:]
    m21, m22, m23 = M[2,:]
    m31, m32, m33 = M[3,:]
    for t =1:T
        x1[1] = m11*x0[1] + m12*x0[2] + m13*x0[3]
        x1[2] = m21*x0[1] + m22*x0[2] + m23*x0[3]
        x1[3] = m31*x0[1] + m32*x0[2] + m33*x0[3]
        x0,x1 = x1,x0
    end
    x0
end

simulate_byhand (generic function with 2 methods)

In [214]:
@time simulate_byhand(M)

  0.103539 seconds (85.14 k allocations: 4.945 MiB, 68.80% compilation time)


3-element Vector{Float64}:
 1.24e-322
 6.0e-323
 6.4e-323